### ISSUE TITLE
Une erreur est survenue, merci de bien vouloir renvoyer le formulaire.

### ISSUE THREAD

**Issue by jcn50** [YunoHost-Apps/paheko_ynh#19]
Il s'agit d'une nouvelle installation, peu importe ce que je mets dans le formulaire après l'installation, j'ai l'erreur suivante:
`Une erreur est survenue, merci de bien vouloir renvoyer le formulaire.`

YunoHost 11.1.18 (stable).
Paheko version: 1.2.8~ynh1

**Comment by rodinux** [comment]
Bonjour, je n'arrive pas à reproduire l'erreur, je viens de tester en local, je n'ai pas eu de soucis...  Pas d'autres logs ?

**Comment by rodinux** [comment]
Un deuxième essai sur un serveur auto-hébergé en production, pas de soucis non plus... 
Est-ce que des caractères spéciaux sont dans le nom de l'association ? Il me semble me rappeler d'avoir eu un soucis avec Écran que j'avais du remplacer par Ecran sans accents...

**Comment by jcn50** [comment]
Bonjour,


> Est-ce que des caractères spéciaux sont dans le nom de l'association ? 

Non, aucun, même pas un accent aigu.

> Sinon essayer de désinstaller et réinstaller... je ne peux pas reproduire ce bug....

Toujours la même chose, j'ai refais 2 fois.

**Comment by jcn50** [comment]
J'ai trouvé. J'ai installé sur `https://$DOMAINE/paheko`: j'ai l'erreur initiale, par contre quand j'installe sur: `https://$SOUSDOMAINE/` ça marche!

**Comment by rodinux** [comment]
> J'ai trouvé. Quand j'installe sur `https://$DOMAINE/paheko`: j'ai l'erreur initiale, par contre quand j'installe sur: `https://$SOUSDOMAINE/` ça marche!

D'accord, par contre tu soulèves tout de même un bug ! 
Bizarre car mes 2 tests cités auparavant étaient sur des adresses `https://$DOMAINE/paheko`

**Comment by jcn50** [comment]
> Tu as d'autres applications installées sur le domaine principal ?

Non je n'ai rien sur le domaine principal: `https://$DOMAINE/`, quand je vais dessus ça me redirige vers: `https://$DOMAINE/yunohost/sso/`
J'ai bien bien pris l'option "Yes" pour "Should this app be exposed to anonymous visitors?" pourtant.

**Comment by jcn50** [comment]
En regardant les Network Calls j'ai ces scripts à la ligne 18 de:
`https://$DOMAINE/paheko/admin/install.php`
qui claquent à cause du SSO:
`<script type="text/javascript" src="/ynh_portal.js"></script><link type="text/css" rel="stylesheet" href="/ynh_overlay.css"><script type="text/javascript" src="/ynhtheme/custom_portal.js"></script><link type="text/css" rel="stylesheet" href="/ynhtheme/custom_overlay.css"></head>`
ils ont des HTTP 302 vers le SSO. Je ne sais pas si ça contribue au bug (ou pas).

**Comment by jcn50** [comment]
J'ai dû refaire l'installation sur le même sous-domaine et j'ai l'erreur à nouveau... Donc il suffit juste de désinstaller et de réinstaller pour avoir l'erreur~

**Comment by jcn50** [comment]
Ahhh~~~ je viens de prendre une fenêtre privée/incognito et ça marche!!

**Comment by jcn50** [comment]
Donc il y a un problème de sessions entre une ancienne et une nouvelle installation~ (il doit y avoir un cookie ou un cache quelque part)

**Comment by jcn50** [comment]
Après plusieurs tests je pense que le problème vient du cache dans le navigateur~~
