### ISSUE TITLE
Comment installer les plugin paheko ?

### ISSUE THREAD

**Issue by joel-jgweb** [YunoHost-Apps/paheko_ynh#26]
**Je voudrais rendre possible la production de fichier PDF proposé par le module tresorerie**
1. *j'ai eu cette erreur en voulant exporter en pdf :
LogicException
Aucun programme de création de PDF trouvé, merci d'en installer un : https://fossil.kd2.org/garradin/wiki?name=Configuration*

**Ce que j'ai essayé de faire**

1. j'ai tenté d'installer le plug-in dompdf.tar.gz 
   - *j'ai copié le fichier en root  dans /var/www/paheko/data/plugins/ *
   - *l'extention est visiblepar le lien https://monsite/admin/config/plugins.php*
   - *lors du lancement de l'installation j'ai le message suivant : Cette extension nécessite l'installation du module PHP zip (apt install php-zip).*
2. *en root j'ai installé sur ynh comme ceci : apt install php-zip*
3. * à la nouvelle tentative d'installation j'ai toujours le message "Cette extension nécessite l'installation du module PHP zip (apt install php-zip)"*

Merci de votre éclairage
---

**Comment by rodinux** [comment]
Bonjour,
 la dépendance php va être celle de l'application, ici Paheko utilise php8.0

https://github.com/YunoHost-Apps/paheko_ynh/blob/e5eef745c1465c56bfd57ccb74f9c9e8f8beb38a/scripts/_common.sh#L9

dans l'idéal, vous pourriez forker l'application, créer une nouvelle branche pour votre besoin et ajouter la dépendance sur cette ligne 

https://github.com/YunoHost-Apps/paheko_ynh/blob/e5eef745c1465c56bfd57ccb74f9c9e8f8beb38a/scripts/_common.sh#L11

`php_dependencies="php${YNH_PHP_VERSION} php${YNH_PHP_VERSION}-sqlite3 php${YNH_PHP_VERSION}-gd php${YNH_PHP_VERSION}-intl  php${YNH_PHP_VERSION}-cli php${YNH_PHP_VERSION}-gnupg php${YNH_PHP_VERSION}-zip"

Ou bien tenter d'installer php8.0-zip, mais il ne faut pas que ce soit une dépendance du système, ça peut créer des conflits. Je recommande plutôt l'autre procédure.

**Comment by rodinux** [comment]
Sinon, est-ce que cette extension sera intégrée à la version 1.3 ?

La branche testing de paheko_ynh est déjà basée sur la version 1.3-rc3, c'est une candidate release, j'attendais la version stable pour la pousser en stable....

La mise à jour fonctionne, par contre je ne sais pas encore pourquoi cela a dupliqué le dossier `data` dans `data/data`

je peux voir  des gros changements ici 

https://fossil.kd2.org/paheko/wiki?name=Changelog/1.3

> Extensions
> 
> Les extensions officielles suivantes ne sont plus supportées et ne fonctionneront pas avec Paheko 1.3, elles seront supprimées lors de la mise à jour :
> 
>     Horaires d'ouvertures (ouvertures) : remplacé par un module fourni par défaut, la configuration est perdue et doit être re-saisie
>     Réservations (reservations) : remplacé par un module fourni par défaut, la configuration et les réservations existantes sont conservées, mais les créneaux devront être re-saisis
>     Git Documents : supprimée, aucun remplacement pour le moment, utilisez webDAV pour faire une copie régulière des documents
> 

Peut-être que ça vaut le coup de tester ? D'ailleurs je pense que je vais ajouter la dépendance php8.2-zip au cas où...

J'en parle sur le forum: https://fossil.kd2.org/paheko/wiki?name=Changelog/1.3

**Comment by rodinux** [comment]
Ceci dit tu peux vérifier avec la commande `apt-cache policy` de mon côté, je n'ai pas de paquet php-zip installé sur un serveur avec pas mal d'applications:

```
root@myserver:~# apt-cache policy php-zip
php-zip:
  Installed: (none)
  Candidate: 2:7.4+76
  Version table:
     2:8.2+93+0~20230409.46+debian11~1.gbpdb4dcc -1
        500 https://packages.sury.org/php bullseye/main amd64 Packages
     2:7.4+76 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages
root@myserver:~# apt-cache policy php8.0-zip
php8.0-zip:
  Installed: (none)
  Candidate: 1:8.0.29-1+0~20230609.54+debian11~1.gbp7b07ff
  Version table:
     1:8.0.29-1+0~20230609.54+debian11~1.gbp7b07ff 500
        500 https://packages.sury.org/php bullseye/main amd64 Package
```

Dans ce cas il suffirait d'installer php8.0-zip.

**Comment by rodinux** [comment]
> La branche testing de paheko_ynh est déjà basée sur la version 1.3-rc3, c'est une candidate release, j'attendais la version stable pour la pousser en stable....
> 
> La mise à jour fonctionne, par contre je ne sais pas encore pourquoi cela a dupliqué le dossier `data` dans `data/data`

Après discussion avec le développeur et plusieurs tests:

 j'ai découvert que ce comportement qui dupliquait le dossier data dans data/data date depuis un moment, sûrement de ma faute, je ne l'avais pas vu avant ! Du coup dans le script upgrade de la version testing, ce dossier sera supprimé, ça fera de la place et cela n'impacte pas l'application.

> D'ailleurs je pense que je vais ajouter la dépendance php8.2-zip au cas où...

Là aussi, bonne nouvelle, nous n'aurons pas besoin de cette dépendance après lui en avoir parlé, sa réponse:

> Tu n'as pas besoin de zip normalement. Seul le plugin DomPDF en avait
> besoin à l'installation, mais je viens de modifier pour ne pas dépendre
> de ça.

**Comment by rodinux** [comment]
Après des tests, pour pouvoir télécharger des recettes en pdf, j'ai du installer wkhtmlopdf
```
apt install wkhtmlopdf
```

et éditer mon fichier `config.local.user.php` pour ajouter la ligne

```
 const PDF_COMMAND = 'wkhtmltopdf';
```

**Comment by rodinux** [comment]
Bon, j'ai le message Cette extension nécessite l'installation du module PHP zip (apt install php-zip).

**Comment by rodinux** [comment]
J'ai tenté `apt install php8.2-zip` et activé Dompdf, mais j'ai des erreurs encore !! Je crois que la bonne solution est la première


> Après des tests, pour pouvoir télécharger des recettes en pdf, j'ai du installer wkhtmlopdf
> 
> ```
> apt install wkhtmlopdf
> ```
>
> et éditer mon fichier `config.local.user.php` pour ajouter la ligne
> 
> ```
>  const PDF_COMMAND = 'wkhtmltopdf';
> ```

**Comment by bohwaz** [comment]
Depuis la 1.3.0 les plugins sont fournis avec Paheko, et "ZipArchive" n'est plus nécessaire normalement pour DomPDF.
