### ISSUE TITLE
Installation warning 

### ISSUE THREAD

**Issue by jarod5001** [YunoHost-Apps/paheko_ynh#43]
Right after installing paheko, the user must go to the app link to create the admin user and the association.
When I launched the installation, I didn't see in the form anything about admin so I supposed that the admin of yunohost was chosen. I left the installation running and I had some work to do. After an hour I opened the app and realised that anyone could run the setup if he knew the address.
So it would be better to have a warning about it before installing.

**Comment by rodinux** [comment]
Yes, I can add an advertisement, you're right. thanks you for this report.

**Comment by rodinux** [comment]
Can you close the issue @jarod5001 ?

**Comment by rodinux** [comment]
Ok, thanks @jarod5001 , let me advise you I have discover the app must be installed on a dedicated domain (root path `/`) to avoid emails working...
