### ISSUE TITLE
checksum mismatch when trying to upgrade to 1.3.4~ynh1

### ISSUE THREAD

**Issue by russulae** [YunoHost-Apps/paheko_ynh#47]
### Describe the bug

I updated paheko yesterday after a few weeks without doing it. the upgrade went well according to the webadmin, but I got an error `TypeError Cannot assign null to property Paheko\Config::$analytical_set_all of type bool` when trying to reach it today. I saw that 1.3.4 was available today so I tried to upgrade but yunohost wasn't able to download the file from the source because of a checksum mismatch :

```
Expected sha256 checksum: fa2ae180551facd5bb75fa2ce975e1b8e481c425625034eadf5fd6b3f361a5ca
Downloaded sha256 checksum: d0811f84d6aecf5e4006337927ff79593ef8bbe337f2111f7158ff59d444781c
Downloaded file size: 1,2M
```

I downloaded the file myself and found the same checksum. I'm wondering where the expected checksum comes from as I can't see it on the source page (there is a "hash" line but I don't know how it is obtained, and it doesn't match with any of those upthere)...

### Context

- Hardware: Old laptop or computer
- YunoHost version:  11.2.8.2 (stable)
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
  - If yes, please explain:
- Using, or trying to install package version/branch: 1.3.4~ynh1
- If upgrading, current package version: 1.3.2~ynh1

### Steps to reproduce
trying to upgrade paheko from the webadmin system update panel

### Expected behavior
yunohost download the latest tar.gz from paheko sources and install it
 
### Logs

https://paste.yunohost.org/raw/ubenufesow

**Comment by bohwaz** [comment]
Hello, désolé :

> J'ai dû re-publier et écraser la version 1.3.4 (et supprimer la 1.3.3)
> car un des fichiers était corrompu et créait un bug pour les gens qui
> faisaient la mise à jour depuis < 1.3.2, sans passer par la 1.3.2.

Du coup le hash a changé.

**Comment by JacquelinDV** [comment]
Même problème en essayant la mise à jour yunohost de 1.3.2 à 1.3.4 (?) il y a 5 mn.

**Comment by rodinux** [comment]
Bon, en effet désolé... J'ai changé le hash, cette fois cela devrait fonctionner !

**Comment by russulae** [comment]
alors peut-etre que c'est trop tot, mais non ca ne marche toujours pas

**Comment by rodinux** [comment]
Oui il faut attendre que ce soit pris en compte dans le dépôt des apps de Yunohost, sûrement quelque heures.

**Comment by russulae** [comment]
d'accord merci !

**Comment by rodinux** [comment]
je change aussi le tag de la version du coup ce sera `1.3.4_ynh2` !

**Comment by russulae** [comment]
je confirme que le problème de mise à jour est réglé, merci !
