### ISSUE TITLE
config.local.php ecrasé après update

### ISSUE THREAD

**Issue by 3fla1416** [YunoHost-Apps/paheko_ynh#49]
Lors de l'update de 1.3.2 vers 1.3.4, le fichier config.local.php est écrasé.
Ce n'était pas le cas avec la 1.3.0, le fichier de config était dans le répertoire "data", c'était plutôt malin et pratique il n'y avait pas à modifier à chaque fois le fichier de config.

Peut t'on retrouver quelque chose d'équivalent ?
Sinon, quel est l'astuce pour éviter ça ?

**Comment by rodinux** [comment]
@3fla1416  J'essaie de remettre en place une possibilité de garder un fichier `config.local.user.php` qui ne serait pas écrasé, cette fois dans le dossier `/home/yunohost.app/data/`. C'est un peu compliqué de penser à toutes les éventualités de mises à jour depuis des versions antécédentes avec les divers changements qui ont eu lieu, mais si tu y tiens tu peux déjà passer par ce PR #50 .
Je dois aussi être sûr que c'est possible et si possible avoir l'accord de @alexAubin et @ericgaspar pour cette modification...
Si tu veux contribuer aussi, bienvenue...

**Comment by 3fla1416** [comment]
Bonjour,

Je vais voir ça dans une VM pour tester.
Depuis quel version je dois faire ça ?
Comment installer une version de test d'un logiciel, downgrader puis re-tester ?
De plus, je suis un utilisateur de redhat, fedora (depuis 20 ans) à la base et ne connais pas trop l'environnement debian et ses commandes d'installations associés.
Je ne sais pas programmer plus que deux trois routines en python ou arduino.

J'ai lu la discussion autour de la problématique et ce n'est pas forcement simple, en plus du home/xxx.app/ qui s'est rajouté avec yunohost.

Pierre

Envoyé avec la messagerie sécurisée [Proton Mail.](https://proton.me/)

**Comment by rodinux** [comment]
Pour te répondre @3fla1416, Yunohost a ses particularités si tu veux tester (je le fais aussi localement) le plus simple est d'utiliser une image Virtualbox comme expliqué dans la doc https://yunohost.org/fr/packaging_apps_virtualbox.

Et pour tester depuis une ancienne version, comme on n'en a pas trop garder dans le dépôt et que le code a pas mal changé par moment, je fais ces étapes:
* j'installe une instance de l'app `garradin` pour commencer (version 1.2.4), 
* ensuite une pré-installation de l'instance qui va créer la base de données association.sqlite, 
* puis je fais la migration de  `garradin` vers `paheko`  comme expliqué dans le dépôt https://github.com/YunoHost-Apps/garradin_ynh/blob/master/README_fr.md#pourquoi-changer-de-nom--1, cela va mettre en place `paheko` avec la version 1.2.8
* Enfin une upgrade avec ma version en cours de développement pour tester `yunohost app upgrade paheko  -u https://github.com/YunoHost-Apps/paheko_ynh/tree/keep-config --debug`

De mon côté j'ai effectué pas mal de tests aussi...

Ne pas hésiter aussi à revenir en arrière, chaque mise à jour de l'app va créer un backup, donc parfois je supprime l'application pour restaurer la version antérieure.

```
yunohost app remove paheko
rm  -r /home/yunohost.app/paheko        # si besoin de aussi supprimer le dossier où se trouve la base de données
yunohost backup list                                   # liste les sauvegardes
yunohost restore paheko-pre-upgrade2 # ou paheko-pre-upgrade1 
``` 


> J'ai lu la discussion autour de la problématique et ce n'est pas forcement simple, en plus du home/xxx.app/ qui s'est rajouté avec yunohost.

En fait au contraire je trouve, le dossier créer dans le `/home/yunohost.app/$app` ne sera pas écraser ni supprimer si on désinstalle l'application. Un peu comme le dossier des données pour l'application nextcloud. Et justement, dans ce dossier se trouvera la base de données `association.sqlite` ainsi que des backups automatiques créés par paheko lors de mises à jour. Surtout cela a permis de configurer l'envoi des email (smtp) envoyé maintenant par l'user de l'application `paheko`. C'est bien pour cela que j'ajoute un fichier `config.local.user.php` pour des configurations personnelles dans ce dossier.

Ma problématique est surtout d'avoir fait beaucoup de changements pas terribles dans des versions précédentes. C'est un peu long, mais pour comprendre, ça peut aider
 
## L'historique:

De la version paheko `1.2.4`  jusqu'à  la version `1.3.0` on avait ajouter 2 fichiers à la racine du dossier d'installation  pour les configs, un pour préserver de constantes liés à yunohost `config.local.yunohost.php` et un autre pour les ajouts personnels `config.local.user.php`, puis dans celui qui est supposé être le fichier de configuration `$install_dir/config.local.php` on ajoutait juste des liens php pour lire ces 2 fichiers.
On peut le voir ici en naviguant dans les commits:
https://github.com/YunoHost-Apps/paheko_ynh/blob/0542d87c5b07be90e44e9db1d62a162f7ebd2326/scripts/install#L104-L107

En réalité il y a eu un soucis, à l'époque le bot de l'application regardait une branche dev de paheko qui testait breaucoup de versions tests avant de finaliser la `1.3.0` qui apportait beaucoup de changement et je me suis retrouver à tester des versions `Candidate Release`  sur la branche stable, ce que j'aurais du éviter. Il y a eu du coup plusieurs versions `1.2.11` jusqu'à`1.2.11~ynh9`, puis pour la `1.3.0` pareillement... De plus entre la `1.2.11~ynh5` et la `1.3.0~ynh*`  je ne sais plus pourquoi j'avais déplacé le fichier de personnalisation dans `$install_dir/data/config.local.user.php`. Bref un beau bordel, j'avoue...

Je demandais aussi de l'aide au développeur de Paheko, car j'avais de comportement inexplicables comme un dossier qui se dupliquait `$install_dir/data/data` sans que je sache par quel mystère !  

Puis on a tout cleaner avec l'aide de @ericgaspar et de @alexAubin il y a quelques mois pour ajouter le `cron.php`, la configuration d'envoi des mail avec l'user de l'application et un code  plus propre ! merci à eux. Tout ce passe dans le fichier de configuration `config.local.php` où on a choisi l'emplacement dossiers, l'important étant que les valeurs avec les variables sont gardées comme des clés.

Maintenant, l'idée de rajouter de nouveau un fichier de configurations personnelles revient et en effet ça me semble judicieux. Je pense que le code commence a être fonctionnel dans le PR #50 

J'essaie encore quelques derniers ajustements...

**Comment by 3fla1416** [comment]
Merci pour le boulot !
Je test ça dès que j'ai le temps.

Effectivement, nous avons besoins de peu de configuration.
const FILE_STORAGE_BACKEND = 'FileSystem';
const FILE_STORAGE_CONFIG = DATA_ROOT . '/files';

surtout quand j'ai vu que la base de données de l'asso, commençait à dépasser les 100 Mo ... et donc moins gourmands pour les duplicata vers un nuage.

Et la commande de génération PDF, que je n'ai pas encore mis en œuvre sur le yunohost.

Pierre

Envoyé avec la messagerie sécurisée [Proton Mail.](https://proton.me/)

**Comment by 3fla1416** [comment]
Je viens de tester, d'une version 1.3.1-ynh1 vers ta version.
Avec le fichier de config dans /home/yunohost.app/paheko/config.local.user.php cela fonction.

Par contre, mais ça viens peux être de chez moi, mon répertoire /home/yunohost.app/paheko/data/files était vide.

Mais je devais les avoir déplacés dans /var/www/paheko/data/files
Une fois copié au bon endroit, cela fonctionne. J'accède aux fichiers depuis paheko.

J'ai essayé depuis une restauration (tjr en 1.3.1-ynh1), donc avec un fichier /home/yunohost.app/paheko/config.local.user.php bien présent et l'ensemble des fichiers (peut-être que la base de donnée est écrasé ?).
Cela fonctionne, je n'ai pas eu besoin de réécrire la config.

Je ne sais pas si c'est prévu, mais il faudra peut-être indiquer que le fichier de config à changé d'endroit lors du passage vers cette update. Peut être prévoir un backup de la config ?

@+

Pierre

Envoyé avec la messagerie sécurisée [Proton Mail.](https://proton.me/)

**Comment by 3fla1416** [comment]
Zut, je viens d'y penser en envoyant le message mais en fait, il faudrait copier tout le répertoire /var/www/paheko/data/ vers /home/yunohost.app/paheko/

Pour que ceux qui utilise déjà la config "FileSystem" récupère de suites les fichiers au bon endroit ? Après si c'est rangé ailleurs, je suis pas certain que ce soit possible.
const FILE_STORAGE_BACKEND = 'FileSystem';

const FILE_STORAGE_CONFIG = DATA_ROOT . '/files';

Est-ce que c'est une bonne idée ?

Pierre

Envoyé avec la messagerie sécurisée [Proton Mail.](https://proton.me/)

**Comment by rodinux** [comment]
Salut, je me rends compte que j'ai essayé de répondre depuis ma boîte mail aux notifs de Github, ce qui est improductif !!

Comme le ticket est fermé, c'est pas top, je te met ci-dessous ici mes réponses

> Salut,
> 
> c'est compliqué ce que tu me demande... J'ai a un moment essayé de copier des données dans /tmp car il peuvent être effacés par la mise à jour. Par exemple le dossier /home/yunohost.app/$app n'est pas encore créer avant si on upgrade depuis une version où il n'existait pas. Le développeur de Paheko m'avait à l'époque expliqué que normalement, on devrait dézipper le dossier de la mise à jour dans un autre dossier et déplacer ensuite les fichiers qui manquent, pas possible avec le process des packages yunohost... J'ai tenté une manip du genre, mais cela n'était vraiment pas terrible. Surtout qu'il faut réaliser que entre certaines versions le fichier `config.local.user.php` était à la racine de l'app puis ensuite dans le dossier data...
> 
> Surtout que là on veut que le dossier plugins lors de l'installation soit toujours à la racine pour recevoir les mises à jour.
> 
> Ton cas est particulier, je serais d'avis de laisser le code ainsi, l'important étant que tu as compris le principe, tes données ne seront pas écraser dans le dossier /home/yunohost.app/$app. Et pour ceux qui ont bidouiller comme toi, c'est comme pour plusieurs apps de Yunohost où on doit un peu mettre les mains à la patte...
> 
> Je serais plutôt d'avis que cette discussion soit sur le forum de Yunohost pour qu'elle puisse être une ressource utile si quelqu'un y est confronté.
> 
> https://forum.yunohost.org/t/paheko-erp-for-non-profit-organization/23699/66
> 
> Par exemple dans ta version de restauration 1.3.1-ynh1 il ne devrait pas y avoir de fichier /home/yunohost.app/paheko/config.local.user.php, il est là juste parce que le dossier /home/yunohost.app/paheko/ lui n'est pas effacer même après un remove. Les bases de données aussi sont dans ce dossier. Du coup tu as un fichier /home/yunohost.app/paheko/data/files/ avec les fichiers téléchargés, c'est bien ça ??
> 
> bonne journée et bonne année
> 
> rodinux

et

> J'ajoute par contre un message dans ADIM.md
> 
> Privilégiez le dossier `__DATA-DIR__/data` si vous voulez conserver des documents ailleurs que dans la base de données. Exemple
> 
> ```
> const FILE_STORAGE_BACKEND = 'FileSystem';
> 
> const FILE_STORAGE_CONFIG = DATA_ROOT . '/files';
> ```

À savoir, j'ai poussé tout cela sur la branche `testing`, J'ai aussi tester la configuration pour les files, ça fonctionne donc j'approuve. Mes questionnements sont avec les permissions des fichiers... Dans le dossier `/home/yunohost.app/data/` par exemple, j'ai ceci

```
ls -l /home/yunohost.app/paheko/data/
total 1768
-rw-r----- 1 paheko www-data 524288 29 déc.  16:20 association.pre-upgrade-1.2.8.sqlite
-rw-r--r-- 1 paheko paheko   524288 29 déc.  16:22 association.pre_upgrade-1.3.5.sqlite
-rw-rw---- 1 paheko www-data 745472 30 déc.  17:24 association.sqlite
drwxr-xr-x 5 paheko www-data   4096 30 déc.  17:24 cache
-rw-r-x--- 1 paheko paheko      566 30 déc.  17:22 config.local.user.php
drwxr-x--- 3 paheko paheko     4096 30 déc.  17:24 files
-rw-r--r-- 1 paheko www-data    189 29 déc.  16:22 index.html
```
J'ai fait exprès que le fichier `index.html` et le dossier `cache` aient les permissions `paheko:www-data` Je ne suis pas sûr que ce soit judicieux que les autres héritent de permissions `paheko:paheko`, ça fonctionne ainsi mais je ne suis pas sûr à vrai dire si cela peut avoir des conséquences malencontreuses...
