### ISSUE TITLE
Offrir la possibilité d'utiliser le serveur smtp "de base" de yunohost

### ISSUE THREAD

**Issue by 3fla1416** [YunoHost-Apps/paheko_ynh#56]
### Describe the bug

Je cherche à configurer au mieux le serveur SMTP pour l’envoi de message par l’application paheko.
Avec l’objectif d’envoyer des messages en “masse” (reçus fiscaux).
L’envoi de message fonctionne mais pas pour toutes les messageries, les boites gmail ne reçoivent même pas le message dans les spams !

La raison, je n’ai pour l’instant pas la main sur un nom de domaine (L’asso est lente à prendre une décision) et je passe par une “url.ynh.fr”, j’ai donc, comme la documentation l’indique, un sous domaine paheko.url.ynh.fr.

J’ai donc fait un test spam chez mail-tester
Comme je m’y attendais, j’ai un score de 2,5/10.

Ce qui n’est pas le cas pour les messages envoyés pour un utilisateur par roundcubes avec pour configuration le serveur de messagerie sur url.ynh.fr. 9/10 (Le dkim ne pouvant pas être configuré sur les adresses en url.ynh.fr)

Par là, j’essaie de modifier la configuration smtp de paheko pour utiliser le serveur mail configuré en retirant les “paheko” de url.ynh.fr ; mais aucun message n’arrive sur une boite mail, je ne sais pas si les messages partent, je n’ai pas d’erreur dans les logs de paheko.

Ma configuration paheko donne ceci (Comparaison avec l’original):

>    const SMTP_HOST = ‘[paheko⋅url⋅ynh.fr](http://xn--pahekourlynh-zd7gd.fr/)’;
>>       const SMTP_HOST = ‘url⋅ynh⋅fr’;

>    const SMTP_USER = ‘paheko’;
>   const SMTP_PASSWORD = ‘xxxxxxxxxxxxxxxxxxxxxxx’;

>    const SMTP_HELO_HOSTNAME = ‘paheko⋅url⋅ynh⋅fr’;
>>        const SMTP_HELO_HOSTNAME = ‘url⋅ynh⋅fr’;

 >   const MAIL_RETURN_PATH = ‘paheko@paheko⋅url⋅ynh⋅fr’;
>>        const MAIL_RETURN_PATH = ‘paheko@url⋅ynh⋅fr’;

>    const MAIL_SENDER = ‘paheko@paheko⋅url⋅ynh⋅fr’;
>>        const MAIL_SENDER = ‘paheko@url⋅ynh⋅fr’;

Mais cela ne sert à rien, il n'y a plus de message qui part...
Donc je sèche sur ma configuration et j'ai remis celle-ci à l'origine.

### Context

- Hardware:  Raspberry Pi at home
- YunoHost version: 10.2.10.3
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

- Avoir une adresse en url.ynh.fr 
- Configurer son reverse dns correctement chez son fournisseur d'accès internet, plus sortir des "spamlist"
- Avoir une adresse en paheko.url.ynh.fr
- Intaller paheko sur l'instance paheko.url.ynh.fr
- Aller chez mail-tester, créer son adresse mail de test
- Créer un membre avec l'adresse mail de test
- Envoyer un message de test spam à ce membre via l'application paheko
- Regarder son mauvais score chez mail-tester. (2,5/10 pour ma part)
- Le comparer avec un envoi d'un utilisateur yunohost standard qui à un meilleur Score (9/10)

### Expected behavior

Pouvoir configurer facilement les paramètres d'envois par le serveur de messagerie "standard" de paheko.
Permettre de changer l'adresse "return" pour voir les messages de retour. Si ils sont réceptionnés, je ne sais pas où ils sont ?
Permettre le choix de l'utilisateur "ynh" admin de paheko concernant les mails du style asso@url.ynh.fr ou autre.

### Logs

Aucun message d'erreur dans error.log de paheko pourtant j'ai bien "const SHOW_ERRORS = true;" dans le fichier de config.

Merci pour votre aide

PS : Doublon avec un message sur le forum yunohost.

**Comment by rodinux** [comment]
Je pense qu'une adresse en `ynh.fr` ne peut avoir qu'un domaine avec le bon spf et le dkim pour l'envoi des mails.

**Comment by zamentur** [comment]
C'est un ticket qui concerne plutôt le core et pas tellement l'app paheko.

Pour envoyer du mail en masse vers les gafams, ça demande pas mal de travail. Mais la base, ce serait déjà d'avoir un nom de domaine et peut être de retoucher la config postfix...
