### ISSUE TITLE
Upgrade failed to Paheko / La migration vers Paheko à échoué

### ISSUE THREAD

**Issue by ilosu** [YunoHost-Apps/paheko_ynh#9]
### Describe the bug

Upgrade failed / La migration à échoué

### Context

- Hardware: VPS bought online / 1vCPU - 1 Go RAM
- YunoHost version: 11.1.7
- I have access to my server: through the webadmin / direct access via proxmox console
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: no
- Using, or trying to install package version/branch: https://github.com/YunoHost-Apps/paheko_ynh/
- If upgrading, current package version: *can be found in the admin, or with `1.2.4~ynh1`*

### Steps to reproduce

```
sudo yunohost app upgrade garradin -u https://github.com/YunoHost-Apps/paheko_ynh --debug
```
    

### Logs

[https://paste.yunohost.org/raw/xewosuxiqe](https://paste.yunohost.org/raw/xewosuxiqe)

**Comment by rodinux** [comment]
Hello, so the migration failed, but you still have keep your Garradin instance restored , c'est bien ça ? 
You haven't loose your datas ?

We have tested on few instances, also in production with no fails, but the application was not yet in the catalog. 
Thanks you for report the issue, there is something to do with this line 

`2023-02-16 14:08:27,300: WARNING - ./upgrade: ligne 91: garradin_migrate_id : variable sans liaison` 
I look to how resolve...

**Comment by rodinux** [comment]
OK, I found what's the matter... we have recently upgrade also garradin to 1.2.4, So I have to change also here a line on the upgrade script here https://github.com/YunoHost-Apps/paheko_ynh/blob/74c0bde1e19953d4cb454b64ac506f25ba981c26/scripts/upgrade#L90

I think you can try if this fix the issue.

**Comment by ilosu** [comment]
Thank you,

It works !

**Comment by rodinux** [comment]
Nice ! wellcome
